# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer', '0002_auto_20171206_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_image', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'banks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('cus_num', models.AutoField(primary_key=True, serialize=False)),
                ('cus_age', models.IntegerField(blank=True, null=True)),
                ('cus_sex', models.IntegerField(blank=True, null=True)),
                ('repayment', models.IntegerField(blank=True, null=True)),
                ('repayment_money', models.FloatField(blank=True, null=True)),
                ('cus_salary', models.FloatField(blank=True, null=True)),
                ('cus_loan', models.FloatField(blank=True, null=True)),
                ('leasing_mortgage', models.FloatField(blank=True, null=True)),
                ('month_loan_period', models.IntegerField(blank=True, null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanGoods',
            fields=[
                ('loan_num', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_good_name', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_int_rat', models.FloatField(blank=True, null=True)),
                ('money_credit_line', models.FloatField(blank=True, null=True)),
                ('rate_credit_line', models.FloatField(blank=True, null=True)),
                ('salary_credit_line', models.FloatField(blank=True, null=True)),
                ('month_loan_period_line', models.IntegerField(blank=True, null=True)),
                ('loan_repayment', models.IntegerField(blank=True, null=True)),
                ('loan_url', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_img', models.CharField(blank=True, max_length=50, null=True)),
                ('num_recommend', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCalc',
            fields=[
                ('calc_num', models.AutoField(primary_key=True, serialize=False)),
                ('like_loan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_calc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCalc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_calc2',
                'managed': False,
            },
        ),
    ]
