# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_banks_'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticAge',
            fields=[
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('m0_20', models.IntegerField(blank=True, null=True)),
                ('m20_30', models.IntegerField(blank=True, null=True)),
                ('m30_40', models.IntegerField(blank=True, null=True)),
                ('m40_50', models.IntegerField(blank=True, null=True)),
                ('m50_60', models.IntegerField(blank=True, null=True)),
                ('m60_0', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistic_age',
                'managed': False,
            },
        ),
    ]
