# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_statisticage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('m1_loan_good_num', models.IntegerField(blank=True, null=True)),
                ('m1_num', models.IntegerField(blank=True, null=True)),
                ('m2_loan_good_num', models.IntegerField(blank=True, null=True)),
                ('m2_num', models.IntegerField(blank=True, null=True)),
                ('m3_loan_good_num', models.IntegerField(blank=True, null=True)),
                ('m3_num', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistic_list',
                'managed': False,
            },
        ),
    ]
