# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_statisticlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='statisticlist',
            options={'managed': True},
        ),
    ]
